#!/usr/bin/env python
import os
import sys
from crewai_tools import MCPServerAdapter
from datadog_monitoring.crew import DatadogMonitoring

# This main file is automatically generated by the Meta-Agent.

def run():
    """Run the crew."""
    inputs = {
        'time_range': 'last 24 hours',
        'output_path': 'report.md',
        'datadog_query': 'service:erody-assist-service',
        'limit': '10',
        'recipient_email': os.environ.get('RECIPIENT_EMAIL', 'p90p53@shinsegae.com'),
    }

    # Connect to the shared MCP server via SSE
    # The Celery worker will start this server at localhost:8012
    server_params = {
        "url": os.environ.get("SHARED_MCP_SERVER_URL", "http://localhost:8012/sse"),
        "transport": "sse"
    }

    try:
        print(f"[MCP Client] Connecting to shared MCP server at {server_params['url']}...")
        with MCPServerAdapter(server_params) as tools:
            print(f"[MCP Client] Connected to shared MCP server. Discovered {len(tools)} tools.")
            DatadogMonitoring(mcp_tools=tools).crew().kickoff(inputs=inputs)
    except Exception as e:
        print(f"[Warning] Failed to connect to shared MCP server ({e}). Falling back to custom_tool.py local executions.", flush=True)
        DatadogMonitoring().crew().kickoff(inputs=inputs)

